"""
html_to_text.py
----------------
Fallback HTML -> plaintext conversion, used ONLY when a fetched message
has no native text/plain MIME part (see imap_client.py's
fetch_plaintext_body).

WHY THIS EXISTS AND WHY IT'S RISKY: classify.py and every parse_*.py
module were built and verified against plaintext bodies pulled through
the Gmail connector's own PLAIN_TEXT conversion, not raw IMAP -- and that
conversion has a very specific quirk the parsers now depend on: HTML
`<table>` rows come back as "| cell | cell |" lines (see
parse_pokemoncenter.py's whole SKU-row-matching design). This module is a
best-effort REPLICA of that specific behavior (table rows -> pipe-joined
cells, block tags -> line breaks), written by inspecting the fixture
shapes already captured, not by inspecting Gmail's actual conversion
code, which isn't available to read.

Real transactional retailer email is usually multipart/alternative WITH a
genuine text/plain part generated by the sending platform (SendGrid,
Braze, Salesforce Marketing Cloud, etc.) -- likely WHY PC's plaintext
looks so mechanically pipe-table-like in the first place, more consistent
with a template-generated plain-text alternative than a generic HTML
render. If that holds, fetch_plaintext_body's text/plain-first preference
means this fallback rarely if ever actually runs for PC or Target mail in
practice.

UNVERIFIED against a real raw IMAP fetch -- there was no live mailbox
connection available while building this (see the email-primary-
architecture memory note). Flagged explicitly as the first thing to spot-
check once a real app password is connected: if PC or Target parsing
starts silently returning [] against live mail where it worked on the
captured fixtures, this function is the first place to look, not the
regexes themselves.
"""

from html.parser import HTMLParser

_BLOCK_TAGS = {"p", "div", "br", "tr", "li", "h1", "h2", "h3", "h4", "h5", "h6"}


class _TableAwareConverter(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self._out: list[str] = []
        self._row_cells: list[str] = []
        self._cell_buf: list[str] = []
        self._in_row = False
        self._in_cell = False
        self._in_script_or_style = False

    def handle_starttag(self, tag: str, attrs) -> None:
        if tag in ("script", "style"):
            self._in_script_or_style = True
        elif tag == "tr":
            self._in_row = True
            self._row_cells = []
        elif tag in ("td", "th"):
            self._in_cell = True
            self._cell_buf = []
        elif tag == "a":
            # A link's own text is real content ("Track status", a
            # product name) -- kept. The href isn't emitted at all: the
            # parsers that consume this text never look for one, and
            # inlining a long tracking URL here would just be noise a
            # regex has to skip past, the same reason every test fixture
            # in this project strips them.
            pass
        elif tag in _BLOCK_TAGS - {"tr"}:
            self._out.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag in ("script", "style"):
            self._in_script_or_style = False
        elif tag in ("td", "th"):
            self._in_cell = False
            self._row_cells.append("".join(self._cell_buf).strip())
        elif tag == "tr":
            self._in_row = False
            if self._row_cells:
                self._out.append("| " + " | ".join(self._row_cells) + " |\n")
        elif tag in _BLOCK_TAGS - {"tr"}:
            self._out.append("\n")

    def handle_data(self, data: str) -> None:
        if self._in_script_or_style:
            return
        if self._in_cell:
            self._cell_buf.append(data)
        else:
            self._out.append(data)

    def text(self) -> str:
        raw = "".join(self._out)
        # Collapse runs of blank lines and trailing spaces the tag-by-tag
        # walk above inevitably produces -- real plaintext mail doesn't
        # have 6 blank lines between rows, and the parsers' own blank-
        # line handling (a "| |" separator row, a paragraph break) is
        # tolerant of one blank line, not an arbitrary run of them.
        lines = [line.rstrip() for line in raw.splitlines()]
        out_lines: list[str] = []
        for line in lines:
            if line == "" and out_lines and out_lines[-1] == "":
                continue
            out_lines.append(line)
        return "\n".join(out_lines).strip("\n")


def html_to_text(html: str) -> str:
    converter = _TableAwareConverter()
    converter.feed(html)
    return converter.text()
