"""add category to orders

Revision ID: 8a8d1bfdaab6
Revises: e12eb6e313c4
Create Date: 2026-08-21 14:54:42.867484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8d1bfdaab6'
down_revision: Union[str, Sequence[str], None] = 'e12eb6e313c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'category')
    # ### end Alembic commands ###
