"""add product_text to inventory_items

Revision ID: 9b0fecfeda6e
Revises: 8a8d1bfdaab6
Create Date: 2026-08-21 15:46:12.504518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0fecfeda6e'
down_revision: Union[str, Sequence[str], None] = '8a8d1bfdaab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('product_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'product_text')
    # ### end Alembic commands ###
