"""add order shipping fields and app_settings table

Revision ID: e12eb6e313c4
Revises: 95e6fc6980b8
Create Date: 2026-08-21 13:38:33.915425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12eb6e313c4'
down_revision: Union[str, Sequence[str], None] = '95e6fc6980b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_app_settings_user_key')
    )
    # server_default matters here, not just the Python-side model default:
    # this ALTER TABLE has to backfill any existing rows too, and SQLite
    # rejects a NOT NULL column added with no way to fill it in.
    op.add_column(
        'orders',
        sa.Column('shipping_status', sa.String(), nullable=False, server_default='not_shipped'),
    )
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('ship_to_label', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('ship_to_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ship_to_address')
    op.drop_column('orders', 'ship_to_label')
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'shipping_status')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
